# Generated by Django 5.0.3 on 2024-03-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
