# Generated by Django 5.0.3 on 2024-03-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='test_taken',
            field=models.BooleanField(default=False),
        ),
    ]
