# Generated by Django 5.0.3 on 2024-03-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_templogin_remove_login_test_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templogin',
            name='tempID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
