# Generated by Django 5.0.3 on 2024-03-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('highestdegree', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10)),
                ('SFID', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('test_taken', models.BooleanField(default=False)),
            ],
        ),
    ]
