# Generated by Django 5.0.3 on 2024-03-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_student_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='degree',
            new_name='rollno',
        ),
    ]
