# Generated by Django 3.2.25 on 2024-04-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_rename_degree_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tabSwitchCount',
            field=models.IntegerField(default=0),
        ),
    ]
