# Generated by Django 5.0.3 on 2024-03-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('B.Tech Mechanical Engineering', 'ME'), ('B.Tech Computer science/ IT', 'CSE'), ('B.Tech Electronics & Telecomm', 'ET'), ('B.Tech Electrical/Electronics', 'EE'), ('M.Tech Mechanical Engineering', 'ME'), ('M.Tech Computer science/ IT', 'CSE'), ('M.Tech Electronics & Telecomm', 'ET'), ('M.Tech Electrical/Electronics', 'EE')], max_length=100)),
            ],
        ),
    ]
