# Generated by Django 5.0.3 on 2024-03-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizquestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option',
            new_name='option2',
        ),
        migrations.AlterField(
            model_name='questions',
            name='department',
            field=models.CharField(choices=[('ME', 'B.Tech Mechanical Engineering'), ('CSE', 'B.Tech Computer science/ IT'), ('ET', 'B.Tech Electronics & Telecomm'), ('EE', 'B.Tech Electrical/Electronics'), ('ME', 'M.Tech Mechanical Engineering'), ('CSE', 'M.Tech Computer science/ IT'), ('ET', 'M.Tech Electronics & Telecomm'), ('EE', 'M.Tech Electrical/Electronics')], max_length=100),
        ),
    ]
