# Generated by Django 5.0.3 on 2024-03-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizquestions', '0002_rename_option_questions_option2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='department',
            field=models.CharField(choices=[('BME', 'B.Tech Mechanical Engineering'), ('BCSE', 'B.Tech Computer science/ IT'), ('BET', 'B.Tech Electronics & Telecomm'), ('BEE', 'B.Tech Electrical/Electronics'), ('MME', 'M.Tech Mechanical Engineering'), ('MCSE', 'M.Tech Computer science/ IT'), ('MET', 'M.Tech Electronics & Telecomm'), ('MEE', 'M.Tech Electrical/Electronics')], max_length=100),
        ),
    ]
