# Generated by Django 5.0.3 on 2024-03-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizquestions', '0003_alter_questions_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='ques',
        ),
    ]
