# Generated by Django 5.0.3 on 2024-03-18 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizquestions', '0004_rename_question_questions_ques'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='ques',
            new_name='question',
        ),
    ]
