# Generated by Django 5.0.3 on 2024-03-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizquestions', '0006_alter_questions_answer_alter_questions_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='department',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('M.S', 'M.S'), ('B.Des', 'B.Des'), ('M.Des', 'M.Des')], max_length=100),
        ),
    ]
