# Generated by Django 5.0.3 on 2024-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizquestions', '0007_alter_questions_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='branch',
            field=models.CharField(choices=[('Applied Mechanics(Fluid Mechanics)', 'Applied Mechanics(Fluid Mechanics)'), ('Artificial Intilligence & Machinie Learning', 'Artificial Intilligence & Machinie Learning'), ('Computer Science Engineering', 'Computer Science Engineering'), ('Design Engineering', 'Design Engineering'), ('Electronics & Telecommunication Engineering', 'Electronics & Telecommunication Engineering'), ('Manufacturing Engineering and Industrial Management', 'Manufacturing Engineering and Industrial Management'), ('Manufacturing Solutions', 'Manufacturing Solutions'), ('Mechanical and Aerospace Engineering', 'Mechanical and Aerospace Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Mechanis & Design', 'Mechanis & Design'), ('Power Electronics & Power Systems', 'Power Electronics & Power Systems'), ('Thermal Engineering', 'Thermal Engineering')], default='Computer Science Engineering', max_length=100),
        ),
    ]
