# Generated by Django 5.0.3 on 2024-03-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizquestions', '0010_alter_questions_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='filename',
            field=models.CharField(default='questionbank.xlsx', max_length=500),
        ),
        migrations.AddField(
            model_name='questions',
            name='take',
            field=models.BooleanField(default=True),
        ),
    ]
