# Generated by Django 5.0.3 on 2024-03-28 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizquestions', '0011_questions_filename_questions_take'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
