# Generated by Django 5.0.3 on 2024-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizquestions', '0012_questions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.CharField(default='2024-03-28 16:08:32', max_length=100),
        ),
    ]
